name: Auto Clock In

on:
  schedule:
    - cron: '0 4 * * 0-4'  # Runs at 9:00 AM IST (UTC+5:30)
  workflow_dispatch:      # Manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run Python script
        run: python clockin.py
